### ISSUE TITLE
support for NAT rules

### ISSUE THREAD

**Issue by m4h3** [gabstopper/ansible-stonesoft#1]
Hey,

It would be nice to have support fw NAT rules.

**Comment by gabstopper** [comment]
Hi Marc,
Already available. Here is the doc:

http://smc-python.readthedocs.io/en/latest/pages/reference.html#ipv4natrule

**Comment by m4h3** [comment]
I'm confused. I'm aware about the smc-python capability, but I don't see an ansible mapping to rule_nat.* objects

**Comment by gabstopper** [comment]
You're right. I was replying from a smc-python perspective. I don't yet
have the NAT in the ansible package. Also, i will update the package
tonight, I think the latest model is more clean than the previous. I've
also collapsed the engine creation so all interfaces can be created in one
fell swoop.

**Comment by gabstopper** [comment]
NAT rules have been added and exist on the develop branch. There is also a howto in the develop based docs link from the README as well.
