### ISSUE TITLE
Traffic Handlers

### ISSUE THREAD

**Issue by meandus** [gabstopper/ansible-stonesoft#12]
Hi,

In the network element, is it possible to create netlink (Traffic Handler) and outbound multilink ?

Thanks

Rémy.

**Comment by gabstopper** [comment]
In smc-python yes, but I will have to add that for the ansible configuration area.

**Comment by meandus** [comment]
And also I need to add a l3fw object to a group.



Le 23 mars 2018 18:10:56 GMT+01:00, David LePage <notifications@github.com> a écrit :
>In smc-python yes, but I will have to add that for the ansible
>configuration area. 
>
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/gabstopper/ansible-stonesoft/issues/12#issuecomment-375736507

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by gabstopper** [comment]
ok. These will be small changes, I will have them ready by Monday.

**Comment by gabstopper** [comment]
Current dev branch implements being able to add engine, expression and alias to group. It's currently on the dev branch. I've now separated the dev branch from master and consider the master branch the 'release' version and will use develop as the ongoing changing branch. Firewall rules have also been added.
