### ISSUE TITLE
Merge conflict markers in the code

### ISSUE THREAD

**Issue by jimlawton** [gabstopper/ansible-stonesoft#17]
There are some merge-conflict markers in the code:
https://github.com/gabstopper/ansible-stonesoft/commit/4069252cc729c090e58b6dd60ebfbac8b6a9867c

**Comment by gabstopper** [comment]
Hi Jim,
Resolved. I also added policy_vpn to the engine_facts output as well. Still need to add the modification of policy_vpn but that's next
