### ISSUE TITLE
OSPF Area

### ISSUE THREAD

**Issue by meandus** [gabstopper/ansible-stonesoft#19]
Hi,

Do you know how to create an OSPF Element (Area, Profiles at least) and Add to the routing table on an Interface Vlan.

Regards,

Rémy Pouchain.

**Comment by gabstopper** [comment]
Hi Remy,
I will add, just finishing up the module so you will be able to add ospf area and ospf profiles. Will let you know when I can push to develop branch.

**Comment by meandus** [comment]
The soonest is better ;)



Le 23 mai 2018 12:36:00 GMT+02:00, David LePage <notifications@github.com> a écrit :
>Hi Remy,
>I will add, just finishing up the module so you will be able to add
>ospf area and ospf profiles. Will let you know when I can push to
>develop branch.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/gabstopper/ansible-stonesoft/issues/19#issuecomment-391301293

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by meandus** [comment]
Good good ! Thanks a lot 

Le 23 mai 2018 12:36:00 GMT+02:00, David LePage <notifications@github.com> a écrit :
>Hi Remy,
>I will add, just finishing up the module so you will be able to add
>ospf area and ospf profiles. Will let you know when I can push to
>develop branch.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/gabstopper/ansible-stonesoft/issues/19#issuecomment-391301293

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by gabstopper** [comment]
Hi Remy,
A new version is posted. You will need to grab it from the develop branch. This is the new release staging branch so I can keep the master branch for the primary release. It is getting closer to a more formal release with versioning. You will also need the latest smc-python as well (from master).

**Comment by gabstopper** [comment]
Hi Remy, I forgot to point you to an example. Here is a yaml for creating OSPF Area and OSPF Profiles: https://github.com/gabstopper/ansible-stonesoft/blob/develop/playbooks/ospf_element.yml

You can also use the ospf_element_facts.yml the same way as the engine.yaml to retrieve an existing element, change and resubmit (or even just use the facts yaml to check for proper syntax and options, remove the ones you don't need and run).

**Comment by meandus** [comment]
And how to add to the routing table ?

Le 25 mai 2018 14:12:40 GMT+02:00, David LePage <notifications@github.com> a écrit :
>Hi Remy, I forgot to point you to an example. Here is a yaml for
>creating OSPF Area and OSPF Profiles:
>https://github.com/gabstopper/ansible-stonesoft/blob/develop/playbooks/ospf_element.yml
>
>You can also use the ospf_element_facts.yml the same way as the
>engine.yaml to retrieve an existing element, change and resubmit (or
>even just use the facts yaml to check for proper syntax and options,
>remove the ones you don't need and run).
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/gabstopper/ansible-stonesoft/issues/19#issuecomment-392034801

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by gabstopper** [comment]
You can add like the BGP setting, from the engine yaml:
https://github.com/gabstopper/ansible-stonesoft/blob/develop/playbooks/l3fw.yml

```yaml
ospf:
  enabled: true
  ospf_profile: Default OSPFv2 Profile
  router_id: 1.1.1.1
  ospf_areas:
  - interface_id: '2.1'
     name: myarea
     #network: 21.21.21.0/24
```
ospf_areas is a list of areas and interface mappings.

**Comment by meandus** [comment]
Ok thanks !

Le 25 mai 2018 14:58:46 GMT+02:00, David LePage <notifications@github.com> a écrit :
>You can add like the BGP setting, from the engine yaml:
>https://github.com/gabstopper/ansible-stonesoft/blob/develop/playbooks/l3fw.yml
>
>```yaml
>ospf:
>  enabled: true
>  ospf_areas:
>  - interface_id: '2.1'
>     name: myarea
>     #network: 21.21.21.0/24
>     ospf_profile: Default OSPFv2 Profile
>     router_id: 1.1.1.1
>```
>ospf_areas is a list of areas and interface mappings.
>
>
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/gabstopper/ansible-stonesoft/issues/19#issuecomment-392050044

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by gabstopper** [comment]
The API won't change when I post this but I am adding better reporting when modifications are made so the 'state' attribute returns a simple list of dicts that indicate 'name', 'type', 'action'. So when you make a modification, you can see what was modified without having to double check in the SMC. It will be transparent to the existing functionality.

**Comment by gabstopper** [comment]
OSPF elements can be created in commit d83da5b.

**Comment by meandus** [comment]
How to add add OSPF Area on a Vlan interface ?
