### ISSUE TITLE
SMC 6.2.3 (vpn_mapping)

### ISSUE THREAD

**Issue by meandus** [gabstopper/ansible-stonesoft#20]
smc.api.exceptions.UnsupportedEngineFeature: Resource requested: 'vpn_mapping' is not available on this element.

fatal: [localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_Kj4hwX/ansible_module_engine_facts.py\", line 577, in <module>\n    main()\n  File \"/tmp/ansible_Kj4hwX/ansible_module_engine_facts.py\", line 574, in main\n    EngineFacts()\n  File \"/tmp/ansible_Kj4hwX/ansible_module_engine_facts.py\", line 553, in __init__\n    is_fact=True)\n  File \"/tmp/ansible_Kj4hwX/ansible_modlib.zip/ansible/module_utils/stonesoft_util.py\", line 429, in __init__\n  File \"/tmp/ansible_Kj4hwX/ansible_module_engine_facts.py\", line 564, in exec_module\n    if engine.name == self.filter]\n  File \"/tmp/ansible_Kj4hwX/ansible_module_engine_facts.py\", line 524, in to_yaml\n    return yaml_cluster(engine)\n  File \"/tmp/ansible_Kj4hwX/ansible_module_engine_facts.py\", line 480, in yaml_cluster\n    policy_vpn = get_policy_vpn(engine)\n  File \"/tmp/ansible_Kj4hwX/ansible_module_engine_facts.py\", line 492, in get_policy_vpn\n    vpn_mappings = engine.vpn_mappings\n  File \"/usr/lib/python2.7/site-packages/smc_python-0.6.1_dev.201802262117-py2.7.egg/smc/core/engine.py\", line 785, in vpn_mappings\n    resource='vpn_mapping'))\n  File \"/usr/lib/python2.7/site-packages/smc_python-0.6.1_dev.201802262117-py2.7.egg/smc/base/mixins.py\", line 28, in make_request\n    raise ex(e)\nsmc.api.exceptions.UnsupportedEngineFeature: Resource requested: 'vpn_mapping' is not available on this element.\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE",
    "rc": 0

**Comment by gabstopper** [comment]
Hi Remy,
Thank you for posting this - I will address backwards compatibility for policy VPN on the engine in next commit (this evening).

**Comment by meandus** [comment]
Hi David,

When do you plan to commit ?

Rémy.

**Comment by gabstopper** [comment]
Just finishing doc and examples, will be today, hopefully in next 2 hours. For OSPF, i've added a module to add/modify/remove OSPF areas and OSPF profiles. I can add the OSPF domain settings and OSPF interface settings (not related to adding OSPF to an engine) after but at least this would enable you use the normal engine JSON and customize an area and profile and add/remove from engine interfaces. Does that work?

**Comment by gabstopper** [comment]
This has been posted. You will want to grab from the develop branch and update to latest smc-python also.

**Comment by gabstopper** [comment]
Resolved in develop branch commit 3955f45
