### ISSUE TITLE
Need to be able to define a contact address on an engine interface

### ISSUE THREAD

**Issue by sebbbastien** [gabstopper/ansible-stonesoft#27]
Hi,

It seems that, in the current state of things (develop branch), it is not possible to define a contact address on an interface when defining a engine.

Do you have a roadmap for this feature?

Best regards,

**Comment by gabstopper** [comment]
Hi Sebastien,
I will look at this alongside of adding the IPSEC enabled on the interface.

**Comment by sebbbastien** [comment]
Thanks a lot

**Comment by sebbbastien** [comment]
Working fine, thanks
