### ISSUE TITLE
ASdot issue

### ISSUE THREAD

**Issue by meandus** [gabstopper/ansible-stonesoft#3]
>   - name: Run the BGP task on myfw
>     register: result
>     bgp:
>       smc_logging:
>         level: 10
>         path: /tmp/ansible-smc.log
>       name: ansiblecluster
>       autonomous_system: '65026.65013'
>       #autonomous_system: '65026'
>       router_id: none
>       announced_networks:
>         network:
>           - 1.1.1.1/23

    _"msg": "Impossible to store the element as-65026.65013. Error converting from 'String' to 'Long' For input string: \"65026.65013\" Details: Error converting from 'String' to 'Long' For input string: \"65026.65013\""_

**I used SMC-python (master) & ansible-stonesoft (master), requests (2.12)**

Rémy

**Comment by meandus** [comment]
neighbor-as should be accepted the same format.

**Comment by gabstopper** [comment]
Will investigate - it did work when I ran a quick test. Will include in next update.

**Comment by gabstopper** [comment]
I suspect you might not have the latest smc-python build for this issue. I just verified again and it works using the AS number. The symptom you are having is because it isn't calling the asdot function from smc.routing.bgp, that only exists in the build I pushed @82b0f54.

**Comment by meandus** [comment]
Ok I'll check it soon. As_dotted function was here in the library.

So ok ok close it if you have rechecked.

I will do the update on my side.


Le 23 février 2018 19:01:02 GMT+01:00, David LePage <notifications@github.com> a écrit :
>I suspect you might not have the latest smc-python build for this
>issue. I just verified again and it works using the AS number. The
>symptom you are having is because it isn't calling the asdot function
>from smc.routing.bgp (that only exists in the build I pushed @82b0f54. 
>
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/gabstopper/ansible-stonesoft/issues/3#issuecomment-368089454

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by gabstopper** [comment]
Hi Remy,
ok, thanks, let me know if you still have the issue on your end. Just want to make sure you weren't still running from an old version in a virtualenv or something. I verified on my end. I'll close this unless I hear otherwise. Working on the other issues. Thanks for the input!
