### ISSUE TITLE
l3fw_cluster

### ISSUE THREAD

**Issue by meandus** [gabstopper/ansible-stonesoft#6]
Hi David,

I tried to add a new interface vlan to an existing FW 
First step: i grab info from engine_facts
i remove all useless infos and add only my new vlan interfaces 

 - name: Create a single layer 3 firewall
   with_dict: "{{ BU }}"
   l3fw_cluster:
     name: ANSIBLEFW
     smc_logging:
       level: 10
       path: /tmp/ansible-smc.log
     comment: FW BUs Mutualisées Netcenter Paris
     interfaces:
     -   cluster_virtual: 1.2.{{ item.value.id }}.22
         interface_id: '4'
         macaddress: 58:7a:4d:02:02:02
         network_value: 1.2.{{ item.value.id }}.16/29
         nodes:
         -   address: 1.2.{{ item.value.id }}.20
             network_value: 1.2.{{ item.value.id }}.16/29
             nodeid: 2
         -   address: 1.2.{{ item.value.id }}.21
             network_value: 1.2.{{ item.value.id }}.16/29
             nodeid: 1
         vlan_id: "{{ '1' + item.value.id|string + '3' }}"
     -   cluster_virtual: 2.3.{{ item.value.id }}.14
         interface_id: '4'
         macaddress: 58:7a:4d:02:02:02
         network_value: 2.3.{{ item.value.id }}.8/29
         nodes:
         -   address: 2.3.{{ item.value.id }}.13
             network_value: 2.3.{{ + item.value.id }}.8/29
             nodeid: 1
         -   address: 2.3.{{ item.value.id }}.12
             network_value: 2.3.{{ item.value.id }}.8/29
             nodeid: 2
         vlan_id: "{{ '2' + item.value.id|string + '2' }}"

When i execute : 

"module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_Nmoudh/ansible_module_l3fw_cluster.py\", line 904, in <module>\n    main()\n  File \"/tmp/ansible_Nmoudh/ansible_module_l3fw_cluster.py\", line 901, in main\n    StonesoftCluster()\n  File \"/tmp/ansible_Nmoudh/ansible_module_l3fw_cluster.py\", line 547, in __init__\n    super(StonesoftCluster, self).__init__(self.module_args, supports_check_mode=True)\n  File \"/tmp/ansible_Nmoudh/ansible_modlib.zip/ansible/module_utils/stonesoft_util.py\", line 300, in __init__\n  File \"/tmp/ansible_Nmoudh/ansible_module_l3fw_cluster.py\", line 802, in exec_module\n    updated, network = delete_vlan_interface(vlan)\n  File **\"/tmp/ansible_Nmoudh/ansible_module_l3fw_cluster.py\", line 409, in delete_vlan_interface\n    if vlan.get('interface_id') != vlan_str]\nUnboundLocalError: local variable 'vlan_str' referenced before assignment\n",**
    "module_stdout": "",
    "msg": "MODULE FAILURE",

what is exactly the process , you tried to remove vlan interface before creating ?

Rémy

**Comment by gabstopper** [comment]
Resolved. I'm working on unittests now, but I was wondering, does it make sense to you to delete interfaces when they are not defined in the YAML? I'm somewhat torn on that one. Meaning, when you run the l3fw_cluster, if the interface exists on the engine and is not defined in yaml, then it will be deleted. The original intent was that the yaml should be the "final" state of the engine.

**Comment by meandus** [comment]
Hi David

Its ok for new firewall but i need to add also some interfaces for  underlay and thats why i need to add interface without to declare all interfaces otherwise for some firewalls i will have a huge ansible conf.



Le 12 mars 2018 18:14:14 GMT+01:00, David LePage <notifications@github.com> a écrit :
>Resolved. I'm working on unittests now, but I was wondering, does it
>make sense to you to delete interfaces when they are not defined in the
>YAML? I'm somewhat torn on that one. Meaning, when you run the
>l3fw_cluster, if the interface exists on the engine and is not defined
>in yaml, then it will be deleted. The original intent was that the yaml
>should be the "final" state of the engine. 
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/gabstopper/ansible-stonesoft/issues/6#issuecomment-372389490

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by meandus** [comment]
The best is to grab infos from cluster add interfaces and replay all. But i dont want to loose any items.

RÉMY POUCHAIN

Le 12 mars 2018 18:14:14 GMT+01:00, David LePage <notifications@github.com> a écrit :
>Resolved. I'm working on unittests now, but I was wondering, does it
>make sense to you to delete interfaces when they are not defined in the
>YAML? I'm somewhat torn on that one. Meaning, when you run the
>l3fw_cluster, if the interface exists on the engine and is not defined
>in yaml, then it will be deleted. The original intent was that the yaml
>should be the "final" state of the engine. 
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/gabstopper/ansible-stonesoft/issues/6#issuecomment-372389490

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by gabstopper** [comment]
Ok, understood. That was my concern as well. So what I will do is add an option to the ansible configuration to 'delete_missing_interfaces' or something similar so that it will not resolve interfaces not in the yaml (i.e. will not delete). Will adjust that. I actually already have this logic in the ansible library but I wasn't 100% sure if it made sense. Thanks for verifying.

**Comment by gabstopper** [comment]
ok, I like your idea / workflow so i've implemented some minor changes to the logic. Everything stays the same with the exception that now i've added a new module parameter `delete_undefined_interfaces` to the module:

Here is a description:
```
delete_undefined_interfaces:
    description:
      - Delete interfaces from engine cluster that are not defined in the YAML file. This can
        be used as a strategy to remove interfaces. One option is to retrieve the full engine
        json using engine_facts as yaml, then remove the interfaces from the yaml and set this
        to True.
    type: bool
    default: false
```

When this is set to true (default: false), the expectation is that any interfaces not defined in the YAML will be deleted.

The idea is that if you wanted to delete interfaces, you should fetch the entire engine configuration (engine_facts) and set `delete_undefined_interfaces` to true in the task, and remove the interfaces you want to remove. Running the task will then remove interfaces from the engine that are not defined in the yaml. This seems to be a good middle ground because it protects you from accidentally removing interfaces unless explicitly setting this parameter.

You can also optionally skip all interface checking/updating on a given run by setting:
`skip_interfaces: true` in a task as well. However doing so will ignore any interface configurations configured in the yaml (might be useful if you just want to change some other setting and ignore resolving differences in the interfaces).

**Comment by gabstopper** [comment]
Hi Remy,
One note I forgot to mention was that I wasnt sure if your indentation was off above but the vlan_id should be level with the interface_id, like this:
```
-   cluster_virtual: 22.22.22.254
    interface_id: '21'
    macaddress: 02:02:02:20:20:20
    network_value: 22.22.22.0/24
    nodes:
    -   address: 22.22.22.1
         network_value: 22.22.22.0/24
         nodeid: 1
     -  address: 22.22.22.2
         network_value: 22.22.22.0/24
         nodeid: 2
     vlan_id: '21'
```

**Comment by meandus** [comment]
I tested with the new feature delete_unassigned false

 - name: Create a single layer 3 firewall
   with_dict: "{{ BU }}"
   l3fw_cluster:
     name: DC_2
     smc_logging:
       level: 10
       path: /tmp/ansible-smc.log
     antivirus: false
     cluster_mode: standby
     comment: FW DC
     default_nat: false
     domain_server_address: []
     file_reputation: false
     delete_undefined_interfaces: false
     interfaces:
     -   cluster_virtual: 10.10.{{ item.value.id }}.22
         interface_id: '4'
         macaddress: 58:7a:4d:02:02:02
         network_value: 10.10.{{ item.value.id }}.16/29
         nodes:
         -   address: 10.10.{{ item.value.id }}.20
             network_value: 10.10.{{ item.value.id }}.16/29
             nodeid: 2
         -   address: 10.10.{{ item.value.id }}.21
             network_value: 10.10.{{ item.value.id }}.16/29
             nodeid: 1
         vlan_id: "{{ '1' + item.value.id|string + '3' }}"
     -   cluster_virtual: 10.20.{{ item.value.id }}.14
         interface_id: '4'
         macaddress: 58:7a:4d:02:02:02
         network_value: 10.20.{{ item.value.id }}.8/29
         nodes:
         -   address: 10.20.{{ item.value.id }}.13
             network_value: 10.20.{{ + item.value.id }}.8/29
             nodeid: 1
         -   address: 10.20.{{ item.value.id }}.12
             network_value: 10.20.{{ item.value.id }}.8/29
             nodeid: 2
         vlan_id: "{{ '2' + item.value.id|string + '2' }}"



UnboundLocalError: local variable 'updated' referenced before assignment

    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_RKUHVd/ansible_module_l3fw_cluster.py\", line 1376, in <module>\n    main()\n  File \"/tmp/ansible_RKUHVd/ansible_module_l3fw_cluster.py\", line 1373, in main\n    StonesoftCluster()\n  File \"/tmp/ansible_RKUHVd/ansible_module_l3fw_cluster.py\", line 702, in __init__\n    super(StonesoftCluster, self).__init__(self.module_args, supports_check_mode=True)\n  File \"/tmp/ansible_RKUHVd/ansible_modlib.zip/ansible/module_utils/stonesoft_util.py\", line 367, in __init__\n  File \"/tmp/ansible_RKUHVd/ansible_module_l3fw_cluster.py\", line 846, in exec_module\n    interfaces, modified = self.update_interfaces(engine)\n  File \"/tmp/ansible_RKUHVd/ansible_module_l3fw_cluster.py\", line 1061, in update_interfaces\n    if updated:\nUnboundLocalError: local variable 'updated' referenced before assignment\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE",
    "rc": 0

**Comment by gabstopper** [comment]
Hi Remy,
Your syntax is incorrect with the vlan_id field, you will have to unindent it to be level with the interface_id indentation, like this:

```
interfaces:
      -   cluster_virtual: 36.36.36.40
          interface_id: '24'
          macaddress: 02:02:02:04:02:08
          network_value: 36.36.36.0/24
          nodes:
          -   address: 36.36.36.1
              network_value: 36.36.36.0/24
              nodeid: 1
          -   address: 36.36.36.2
              network_value: 36.36.36.0/24
              nodeid: 2
          vlan_id: '21'
```
I will add extra validation to catch that sooner in the ansible run.

**Comment by meandus** [comment]
Hi David,

But it is at the same level of interface_id



Le 13 mars 2018 16:59:22 GMT+01:00, David LePage <notifications@github.com> a écrit :
>Hi Remy,
>Your syntax is incorrect with the vlan_id field, you will have to
>unindent it to be level with the interface_id indentation, like this:
>
>```
>interfaces:
>      -   cluster_virtual: 36.36.36.40
>          interface_id: '24'
>          macaddress: 02:02:02:04:02:08
>          network_value: 36.36.36.0/24
>          nodes:
>          -   address: 36.36.36.1
>              network_value: 36.36.36.0/24
>              nodeid: 1
>          -   address: 36.36.36.2
>              network_value: 36.36.36.0/24
>              nodeid: 2
>          vlan_id: '21'
>```
>I will add extra validation to catch that sooner in the ansible run.
>
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/gabstopper/ansible-stonesoft/issues/6#issuecomment-372717810

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by gabstopper** [comment]
Something is strange, I can duplicate it only if the vlan_id isn't nested properly. Otherwise with the latest version I do not see the same problem. 
The undefined variable should not happen on the latest - it only appears to happen if something interrupts in update_interfaces, or it appears that if the vlan cannot be found in the yaml (invalid nesting). Can you make a run with -vvv and also set me a clip of the /tmp/ansible-smc.log? 
The -vvv output will show the dict that it creates and should look like this:
```
"interfaces": [
                {
                    "cluster_virtual": "36.36.36.40", 
                    "interface_id": "24", 
                    "macaddress": "02:02:02:04:02:08", 
                    "network_value": "36.36.36.0/24", 
                    "nodes": [
                        {
                            "address": "36.36.36.1", 
                            "network_value": "36.36.36.0/24", 
                            "nodeid": 1
                        }, 
                        {
                            "address": "36.36.36.2", 
                            "network_value": "36.36.36.0/24", 
                            "nodeid": 2
                        }
                    ], 
                    "vlan_id": "21"
                }
            ], 
```
Wondering if something is catching an exception and it's somehow being suppressed.  I'll keep looking on my end as well.
Just to verify, this is only adding a new VLAN that doesn't exist?

**Comment by gabstopper** [comment]
I've added validation around the yaml nodes configuration so even if nesting is not correct, the task will fail before being able to run. The only path I can see that the above state would be triggered is if a VLAN id was specified but subsequently not found due to nesting. This is now checked. Please grab the latest l3fw_cluster.py and let me know if that solves the issue for you.

**Comment by gabstopper** [comment]
Hi Remy,
Just fyi, I am about 50% complete with a full unittest against this module (amongst others) to catch some of these edge cases. Let me know if the above still works for you but I will have another update tomorrow that will have a full barrage of tests against it.

**Comment by meandus** [comment]
seems good now to create cluster interfaces but how can i put a comment on Interface ?

**Comment by meandus** [comment]
For new interfaces on existing fw is passed fine !

But i did not find the attribute for comment on interface.

Tomorriw i will update the new scenario for full rbvpn implementation and i will tell you how is.

My underlay with cisco bgp ospf and stonesoft is good.

Thanks a lot for your help.

RÉMY POUCHAIN.

Le 14 mars 2018 04:41:13 GMT+01:00, David LePage <notifications@github.com> a écrit :
>Hi Remy,
>Just fyi, I am about 50% complete with a full unittest against this
>module (amongst others) to catch some of these edge cases. Let me know
>if the above still works for you but I will have another update
>tomorrow that will have a full barrage of tests against it.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/gabstopper/ansible-stonesoft/issues/6#issuecomment-372894905

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by gabstopper** [comment]
Hi Remy,
I have updated both the ansible l3fw_cluster and engine_facts modules this evening with support for comments on the interface. You will also need to pull the latest smc-python as well.
Let me know how that goes. I am interested in where you are with the rbvpn, I suspect we might still need to sort the route map policy bits still.

**Comment by meandus** [comment]
Hi

Seems ignored for interface vlan. I push comment and there is no comment through SMC.

Regards,
RÉMY POUCHAIN

Le 16 mars 2018 04:29:39 GMT+01:00, David LePage <notifications@github.com> a écrit :
>Hi Remy,
>I have updated both the ansible l3fw_cluster and engine_facts modules
>this evening with support for comments on the interface. You will also
>need to pull the latest smc-python as well.
>Let me know how that goes. I am interested in where you are with the
>rbvpn, I suspect we might still need to sort the route map policy bits
>still.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/gabstopper/ansible-stonesoft/issues/6#issuecomment-373592967

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by meandus** [comment]
My bad smcpython was not correctly updated

Le 16 mars 2018 04:29:39 GMT+01:00, David LePage <notifications@github.com> a écrit :
>Hi Remy,
>I have updated both the ansible l3fw_cluster and engine_facts modules
>this evening with support for comments on the interface. You will also
>need to pull the latest smc-python as well.
>Let me know how that goes. I am interested in where you are with the
>rbvpn, I suspect we might still need to sort the route map policy bits
>still.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/gabstopper/ansible-stonesoft/issues/6#issuecomment-373592967

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by gabstopper** [comment]
Sounds good. This one appears to be resolved now.

**Comment by gabstopper** [comment]
Since this was related to the interface and comments, I will close so I can focus on the other open cases.
