### ISSUE TITLE
management interface

### ISSUE THREAD

**Issue by meandus** [gabstopper/ansible-stonesoft#7]
"msg": "Management interface is not defined. Management was specified on interface: 0.608"

 {
                    "cluster_virtual": "2.2.2.1",
                    "comment": "Internet",
                    "interface_id": "0",
                    "macaddress": "16:03:18:09:59:00",
                    "network_value": "2.2.2.0/24",
                    "nodes": [
                        {
                            "address": "2.2.2.3",
                            "network_value": "2.2.2.0/24",
                            "nodeid": 1
                        },
                        {
                            "address": "2.2.2.2",
                            "network_value": "2.2.2.0/24",
                            "nodeid": 2
                        }
                    ],
                    "vlan_id": "608"
                }

**Comment by gabstopper** [comment]
Hi Remy,
This is normal if trying to create the engine with a VLAN interface as management. The engine create constructor currently expects a non-VLAN interface id but I can address that. In the meantime, specify a non-VLAN interface and then move it to the VLAN interface using the:
```
primary_mgt: 0.608
```
field. I will address in smc-python to allow during engine creation.

**Comment by gabstopper** [comment]
I have a fix for this, will post but looking at other issues first.

**Comment by gabstopper** [comment]
Hi Remy,
This has been resolved in the latest commit this evening. You will need to update smc-python and the ansible library as well. It is now possible to create clusters specifying a VLAN id for primary mgt.

**Comment by gabstopper** [comment]
Creating an interface with a VLAN interface is now possible with commit 3d3fe94.
